### ISSUE TITLE
[Enhancement] Add Start button to pause game

### ISSUE THREAD

**Issue by SofyUchiha** [Rinnegatamante/funky_vita#1]
Hi Rinne. How are you? First of all thank you for all your work <3 I loved having this game on my Vita.
I wanted to make a small suggestion. Is it possible to add the Start button to pause the game? 
I know this one only has touch controls. But while playing it is a bit complicated to press the blue button (bottom right) to pause the game. Sometimes you have to make several attempts until it responds.
A big hug!

**Comment by Rinnegatamante** [comment]
Done and available in v.1.1

**Comment by SofyUchiha** [comment]
Thank you so much!
